name: Test GitHub App

on:
  workflow_dispatch:

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
    - name: Generate App Token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ steps.generate_token.outputs.token }}
        repository: arushsharma24/project-ideas
        ref: main
        path: .github/my-project-ideas

    - name: Test App Permissions
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        echo "Testing repository access..."
        ls .github/my-project-ideas

        echo "Testing file creation..."
        echo "This file was created by the GitHub App" > test_file.txt
        git config user.name "Sherlock"
        git config user.email "sherlock@example.com"
        git add test_file.txt
        git commit -m "Test commit by GitHub App"
        git push
